update 2024-12-13 00:14:17

diff --git a/.github/workflows/build-x86-64-openwrt.yml b/.github/workflows/build-x86-64-openwrt.yml
--- a/.github/workflows/build-x86-64-openwrt.yml
+++ b/.github/workflows/build-x86-64-openwrt.yml
@@ -1,35 +1,86 @@
 name: build x86/64 openwrt
 
 on:
+#  schedule: [cron: 30 14 */3 * *]
+#  watch:
+#    types: started
   workflow_dispatch:
-  schedule:
-    - cron: 30 14 */3 * *
-  watch:
-    types: started
+    inputs:
+      source:
+        description: '选择要编译的LUCI版本'
+        required: true
+        default: '18.06'
+        type: choice
+        options: [18.06, 23.05]
 
-env:
-  CLASH_KERNEL: amd64
-  CACHE_TOOLCHAIN: true
-  UPLOAD_BIN_DIR: false
-  UPLOAD_ARTIFACT: true
-  UPLOAD_RELEASE: true
-  TZ: Asia/Shanghai
+      target:
+        description: '选择要编译的机型'
+        required: true
+        default: 'x86-64'
+        type: choice
+        options: [x86-64]
+
+      ip:
+        description: '设置默认登录IP'
+        required: false
+        default: '192.168.1.2'
+
+      partsize:
+        description: '设置rootfs大小'
+        required: false
+        default: '800'
+
+      toolchain:
+        description: '使用toolchain缓存'
+        required: false
+        default: true
+        type: boolean
+
+      zsh_tool:
+        description: '预设zsh终端工具'
+        required: false
+        default: true
+        type: boolean
+
+      openclash:
+        description: '预设openclash内核'
+        required: false
+        default: 'amd64'
+
+      artifact:
+        description: '上传固件到Artifact'
+        required: false
+        default: true
+        type: boolean
+
+      release:
+        description: '上传固件到Releases'
+        required: false
+        default: true
+        type: boolean
 
 jobs:
   build:
     runs-on: ubuntu-22.04
-    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
-    name: build ${{ matrix.target }} ${{ matrix.branch }}
-    strategy:
-      fail-fast: false
-      matrix:
-        target: [x86-64]
-        branch: [18.06, 23.05]
+    name: build ${{ github.event.inputs.target }} ${{ github.event.inputs.source }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        target: [x86-64]
+#        branch: [18.06, 23.05]
 
     env:
-      CONFIG_FILE: configs/${{ matrix.target }}-${{ matrix.branch }}.config
-      DIY_SCRIPT: diy-${{ matrix.branch }}.sh
-      RELEASE_TAG: ${{ matrix.target }}-${{ matrix.branch }}
+#      TARGET_DEVICE: ${{ github.event.inputs.target }}
+      DEFAULT_IP: ${{ github.event.inputs.ip }}
+      PART_SIZE: ${{ github.event.inputs.partsize }}
+      ZSH_TOOL: ${{ github.event.inputs.zsh_tool }}
+      CLASH_KERNEL: ${{ github.event.inputs.openclash }}
+      CONFIG_FILE: configs/${{ github.event.inputs.target }}-${{ github.event.inputs.source }}.config
+      DIY_SCRIPT: diy-${{ github.event.inputs.source }}.sh
+      RELEASE_TAG: ${{ github.event.inputs.target }}-${{ github.event.inputs.source }}
+      TOOLCHAIN_TAG: toolchain
+      UPLOAD_BIN_DIR: false
+      TZ: Asia/Shanghai
 
     steps:
     - name: Checkout
@@ -37,12 +88,16 @@ jobs:
 
     - name: Set Compile Source Code
       run: |
-        if [[ ${{ matrix.branch }} == '18.06' ]]; then
+        if [[ ${{ github.event.inputs.source }} == '18.06' ]]; then
           echo "REPO_URL=https://github.com/coolsnowwolf/lede" >>$GITHUB_ENV
           echo "REPO_BRANCH=master" >>$GITHUB_ENV
-        elif [[ ${{ matrix.branch }} == '23.05' ]]; then
+        elif [[ ${{ github.event.inputs.source }} == '23.05' ]]; then
           echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >>$GITHUB_ENV
           echo "REPO_BRANCH=openwrt-23.05" >>$GITHUB_ENV
+        fi
+        if [ $PART_SIZE ]; then
+          sed -i '/ROOTFS_PARTSIZE/d' $CONFIG_FILE
+          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=$PART_SIZE" >>$CONFIG_FILE
         fi
 
     - name: Check Server Performance
@@ -126,13 +181,23 @@ jobs:
         KERNEL_VERSION=$(sed -n 2p include/kernel-$KERNEL | awk '{print $1}' | awk -F '-' '{print $2}')
         echo "KERNEL_VERSION=$KERNEL_VERSION" >>$GITHUB_ENV
 
-    - name: Cache Toolchain
-      if: env.CACHE_TOOLCHAIN == 'true'
-      uses: HiGarfield/cachewrtbuild@main
-      with:
-        ccache: false
-        mixkey: ${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}
-        prefix: ${{ env.OPENWRT_PATH }}
+    - name: Prepare Toolchain
+      if: github.event.inputs.toolchain == 'true'
+      id: tools
+      run: |
+        cd $OPENWRT_PATH
+        TOOLS_HASH=$(git log --pretty=tformat:"%h" -n1 tools toolchain)
+        CACHE_NAME="$SOURCE_REPO-${REPO_BRANCH#*-}-$DEVICE_TARGET-cache-$TOOLS_HASH"
+        echo "CACHE_NAME=$CACHE_NAME" >>$GITHUB_ENV
+        wget -q https://github.com/$GITHUB_REPOSITORY/releases/download/$TOOLCHAIN_TAG/$CACHE_NAME.tzst || true
+        if [ -e *.tzst ]; then
+          tar -I unzstd -xf *.tzst || tar -xf *.tzst
+          [ -d staging_dir ] && sed -i 's/ $(tool.*\/stamp-compile)//' Makefile || \
+          echo -e "\e[1;31m解压Toolchain缓存失败\e[0m"
+        else
+          echo -e "\e[1;33m没有找到最新的Toolchain缓存，开始重新编译\e[0m"
+          echo "REBUILD_TOOLCHAIN=true" >>$GITHUB_OUTPUT
+        fi
 
     - name: Install Feeds
       run: |
@@ -151,6 +216,40 @@ jobs:
         cd $OPENWRT_PATH
         $GITHUB_WORKSPACE/$DIY_SCRIPT
 
+    - name: Compile Toolchain
+      if: steps.tools.outputs.REBUILD_TOOLCHAIN == 'true' || github.event.inputs.toolchain == 'false'
+      id: toolchain
+      run: |
+        mkdir -p $GITHUB_WORKSPACE/output
+        cd $OPENWRT_PATH
+        make toolchain/compile -j$(nproc) || make toolchain/compile -j1 V=s
+        sed -i 's/ $(tool.*\/stamp-compile)//' Makefile
+        echo -e "\e[1;33m开始打包toolchain目录\e[0m"
+        [ -d ".ccache" ] && (ccache=".ccache"; ls -alh .ccache)
+        tar -I zstdmt -cf $GITHUB_WORKSPACE/output/$CACHE_NAME.tzst staging_dir/host* staging_dir/tool* $ccache
+        ls -lh $GITHUB_WORKSPACE/output
+        [ -e $GITHUB_WORKSPACE/output/$CACHE_NAME.tzst ]
+
+    - name: Delete Old Toolchain
+      if: steps.toolchain.conclusion == 'success'
+      uses: mknejp/delete-release-assets@v1
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        tag: ${{ env.TOOLCHAIN_TAG }}
+        assets: '${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}*'
+        fail-if-no-assets: false
+        fail-if-no-release: false
+
+    - name: Upload Toolchain To Release
+      if: steps.toolchain.conclusion == 'success'
+      uses: softprops/action-gh-release@master
+      with:
+        name: toolchain-cache
+        tag_name: ${{ env.TOOLCHAIN_TAG }}
+        token: ${{ secrets.GITHUB_TOKEN }}
+        files: output/*
+        body: OpenWrt 工具链缓存
+
     - name: Download DL Package
       run: |
         cd $OPENWRT_PATH
@@ -166,8 +265,6 @@ jobs:
         cp $GITHUB_WORKSPACE/scripts/init-settings.sh files/etc/uci-defaults/99-init-settings
         echo -e "$(nproc) thread compile"
         make -j$(nproc) || make -j1 V=s
-        DEFAULT_IP=$(cat package/base-files/files/bin/config_generate | grep 'n) ipad' | cut -d '"' -f2)
-        echo "DEFAULT_IP=$DEFAULT_IP" >>$GITHUB_ENV
         echo "FILE_DATE=$(date +"%Y.%m.%d")" >>$GITHUB_ENV
         echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >>$GITHUB_ENV
 
@@ -194,14 +291,14 @@ jobs:
         echo "FIRMWARE_PATH=$PWD" >>$GITHUB_ENV
 
     - name: Upload Firmware To Artifact
-      if: steps.compile.conclusion == 'success' && env.UPLOAD_ARTIFACT == 'true'
+      if: steps.compile.conclusion == 'success' && github.event.inputs.artifact == 'true'
       uses: actions/upload-artifact@main
       with:
         name: ${{ env.SOURCE_REPO }}-${{ env.LITE_BRANCH }}-${{ env.DEVICE_TARGET }}-firmware-${{ env.FILE_DATE }}
         path: ${{ env.FIRMWARE_PATH }}
 
     - name: Upload Firmware To Release
-      if: steps.compile.conclusion == 'success' && env.UPLOAD_RELEASE == 'true'
+      if: steps.compile.conclusion == 'success' && github.event.inputs.release == 'true'
       uses: ncipollo/release-action@main
       with:
         name: ${{ env.DATE }} for ${{ env.DEVICE_TARGET }}
